### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by ghost** [vinyll/certbot-install#2]
I use "fresh" Ubuntu 20.04 minimal (Hetzner hosting company) 
There is an error:

```
ERROR: Command errored out with exit status 1:
   command: /root/.certbot-src/venv3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ocmtkyda/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ocmtkyda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vtn5gg3p
       cwd: /tmp/pip-req-build-ocmtkyda/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pip
```

**Comment by vinyll** [comment]
Wheel should have been installed.

You may manually install it:

```
~/.certbot-src/venv3/bin/pip install wheel
```

**Comment by ghost** [comment]
```wheel``` is installed, but it doesn't work (still as in the first post)
```
root@vds:~/certbot/venv3/bin# pip3 install wheel
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
```
```
root@vds:~/certbot/venv3/bin# ./pip install wheel
Requirement already satisfied: wheel in /root/certbot/venv3/lib/python3.8/site-packages
```

**Comment by vinyll** [comment]
I've [added dependencies explicitly](https://github.com/vinyll/certbot-install/commit/ea764ccab5629e59390cb00bea4d6908d0e9d1dc).
Can you try to run the install script again?

**Comment by vinyll** [comment]
I'll close this for inactivity and will reopen if error occurs again.

**Comment by ustczzh** [comment]
same thing still happen for me on two ubuntu 20.04, and I've tried ~/.certbot-src/venv3/bin/pip install wheel.

+ /root/.certbot-src/venv3/bin/python /root/.certbot-src/letsencrypt-auto-source/pieces/pipstrap.py
  ERROR: Command errored out with exit status 1:
   command: /root/.certbot-src/venv3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xg_28fyr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xg_28fyr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-c1o81bag
       cwd: /tmp/pip-req-build-xg_28fyr/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pip
